### ISSUE TITLE
Error enabling FactoryMod

### ISSUE THREAD

**Issue by wingzero54** [CivMC/FactoryMod#18]
[02:30:26] [Server thread/ERROR]: Error occurred while enabling FactoryMod v3.0.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/inventory/CraftItemStack
	at vg.civcraft.mc.civmodcore.inventory.items.ItemUtils.getNMSItemStack(ItemUtils.java:182) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at vg.civcraft.mc.civmodcore.nbt.NBTSerialization.processItem(NBTSerialization.java:75) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at vg.civcraft.mc.civmodcore.inventory.items.ItemMap.enrichWithNBT(ItemMap.java:636) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at vg.civcraft.mc.civmodcore.config.ConfigHelper.parseItemMapDirectly(ConfigHelper.java:276) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at vg.civcraft.mc.civmodcore.config.ConfigHelper.parseItemMap(ConfigHelper.java:137) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at com.github.igotyou.FactoryMod.ConfigParser.parseRecipe(ConfigParser.java:733) ~[FactoryMod-paper-3.0.0-SNAPSHOT.jar:?]
	at com.github.igotyou.FactoryMod.ConfigParser.parseRecipes(ConfigParser.java:243) ~[FactoryMod-paper-3.0.0-SNAPSHOT.jar:?]
	at com.github.igotyou.FactoryMod.ConfigParser.parse(ConfigParser.java:158) ~[FactoryMod-paper-3.0.0-SNAPSHOT.jar:?]
	at com.github.igotyou.FactoryMod.FactoryMod.onEnable(FactoryMod.java:21) ~[FactoryMod-paper-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-333]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 20 more

**Comment by nebula161** [comment]
Ran into this about an hour ago, is there a slightly older version that works?

**Comment by wingzero54** [comment]
> Ran into this about an hour ago, is there a slightly older version that works?

I'm pretty sure the 1.18.1 version of FactoryMod worked on Paper 1.18.1, this may be a 1.18.2 issue

**Comment by Diet-Cola** [comment]
This is down to an out of date CivModCore/FactoryMod
