### ISSUE TITLE
Massive error upon running /fm  and related commands

### ISSUE THREAD

**Issue by nebula161** [CivMC/FactoryMod#19]
Not sure why the formatting is like that.
`[23:28:18 ERROR]: [FactoryMod] [ACF] Exception in command: fm 
[23:28:18 ERROR]: [FactoryMod] [ACF] java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/util/CraftChatMessage
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//vg.civcraft.mc.civmodcore.chat.ChatUtils.stringify(ChatUtils.java:304)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//vg.civcraft.mc.civmodcore.inventory.items.ItemUtils.getItemName(ItemUtils.java:47)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.utility.FactoryModGUI.showFactoryOverview(FactoryModGUI.java:101)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.commands.FactoryMenu.execute(FactoryMenu.java:25)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//co.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at CivModCore-paper-2.0.0-SNAPSHOT.jar//co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[23:28:18 ERROR]: [FactoryMod] [ACF]    at java.base/java.lang.Thread.run(Thread.java:833)
[23:28:18 ERROR]: [FactoryMod] [ACF] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.util.CraftChatMessage
[23:28:18 ERROR]: [FactoryMod] [ACF]    ... 34 more`

**Comment by wingzero54** [comment]
Please update FactoryMod and CivModCore based on latest repo or jars here https://github.com/CivMC/CivDocker/tree/master/paper/plugins

**Comment by wingzero54** [comment]
Closing as this should be resolved by my above message.
