### ISSUE TITLE
Error saving factory data

### ISSUE THREAD

**Issue by wingzero54** [CivMC/FactoryMod#21]
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/ERROR]: [FactoryMod] Fatal error while trying to save factory data
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=55, y=76, z=-26},type=FURNACE,data=Block{minecraft:furnace}[facing=west,lit=false],fluid=net.minecraft.world.level.material.FluidTypeEmpty@14a00898}
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:89)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:75)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:263)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:221)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:206)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlock.getState(CraftBlock.java:329)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.factories.FurnCraftChestFactory.getFacing(FurnCraftChestFactory.java:214)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.factories.FurnCraftChestFactory.getTableIOSelector(FurnCraftChestFactory.java:188)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.utility.FileHandler.save(FileHandler.java:103)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.FactoryModManager.saveFactories(FactoryModManager.java:459)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at FactoryMod-paper-3.0.0-SNAPSHOT.jar//com.github.igotyou.FactoryMod.ConfigParser$1.run(ConfigParser.java:138)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:55:36] [Craft Scheduler Thread - 96 - FactoryMod/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Diet-Cola** [comment]
Was this just on normal shutdown? I've never seen this error

**Comment by wingzero54** [comment]
No I created a factory and ran it a couple times, and saw this in the log around the same time. I did do it through /fmc and /fmco but I don't see why that would cause an issue

**Comment by Diet-Cola** [comment]
Havent heard anymore of this, assume this was one off / maybe caused by Docker killing?

**Comment by wingzero54** [comment]
Yeah I haven't seen this since, so I'll chalk it up to unknown resolved issue
